name: Python Test and Docker Deployment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Change to the version of Python you are using

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Step 4: Run tests
    - name: Run tests
      run: |
        pip install -r tests/requirements.txt # install pytest
        pytest tests/  # Change this command if you're using a different test runner

  build:
    runs-on: ubuntu-latest
    needs: test
    if: success()  # Only runs if the "test" job succeeds

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up Docker
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    # Step 3: Build Docker image
    - name: Build Docker image
      run: |
        docker build -t your-image-name .

    # Step 4: Run Docker container
    - name: Run Docker container
      run: |
        docker run -d -p 8501:8501 your-image-name  # Change ports as needed
